CREATE TABLE IF NOT EXISTS faq (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  question_fr TEXT NOT NULL,
  question_en TEXT,
  question_it TEXT,
  question_es TEXT,
  question_de TEXT,
  answer_fr TEXT NOT NULL,
  answer_en TEXT,
  answer_it TEXT,
  answer_es TEXT,
  answer_de TEXT,
  sort_order INTEGER DEFAULT 0,
  published BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE faq ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read faq" ON faq FOR SELECT USING (true);
CREATE POLICY "Auth manage faq" ON faq FOR ALL USING (auth.role() = 'authenticated');

-- Seed with existing FAQ data
INSERT INTO faq (question_fr, question_en, question_it, question_es, question_de, answer_fr, answer_en, answer_it, answer_es, answer_de, sort_order, published) VALUES
('Quels sont vos horaires d''ouverture ?', 'What are your opening hours?', 'Quali sono gli orari di apertura?', '¿Cuáles son sus horarios de apertura?', 'Was sind Ihre Öffnungszeiten?', 'Nos horaires varient selon la saison. Consultez notre page contact ou appelez-nous au 04 48 17 78 75 pour connaître les horaires actuels.', 'Our opening hours vary by season. Please check our contact page or call us at 04 48 17 78 75 for current hours.', 'I nostri orari variano in base alla stagione. Consultate la nostra pagina contatti o chiamateci al 04 48 17 78 75 per gli orari attuali.', 'Nuestros horarios varían según la temporada. Consulte nuestra página de contacto o llámenos al 04 48 17 78 75 para conocer los horarios actuales.', 'Unsere Öffnungszeiten variieren je nach Saison. Besuchen Sie unsere Kontaktseite oder rufen Sie uns unter 04 48 17 78 75 an.', 1, true),
('Comment réserver une table ?', 'How can I book a table?', 'Come posso prenotare un tavolo?', '¿Cómo puedo reservar una mesa?', 'Wie kann ich einen Tisch reservieren?', 'Vous pouvez réserver directement sur notre site web via le formulaire de réservation, ou par téléphone au 04 48 17 78 75.', 'You can book directly on our website through the reservation form, or by phone at 04 48 17 78 75.', 'Potete prenotare direttamente sul nostro sito web tramite il modulo di prenotazione, o telefonicamente al 04 48 17 78 75.', 'Puede reservar directamente en nuestro sitio web a través del formulario de reserva, o por teléfono al 04 48 17 78 75.', 'Sie können direkt auf unserer Website über das Reservierungsformular buchen oder telefonisch unter 04 48 17 78 75.', 2, true),
('Proposez-vous des options végétariennes ?', 'Do you offer vegetarian options?', 'Offrite opzioni vegetariane?', '¿Ofrecen opciones vegetarianas?', 'Bieten Sie vegetarische Optionen an?', 'Oui, notre carte propose plusieurs plats végétariens. N''hésitez pas à nous signaler vos préférences alimentaires lors de la réservation.', 'Yes, our menu features several vegetarian dishes. Please let us know about your dietary preferences when booking.', 'Sì, il nostro menu propone diversi piatti vegetariani. Non esitate a segnalarci le vostre preferenze alimentari al momento della prenotazione.', 'Sí, nuestra carta ofrece varios platos vegetarianos. No dude en indicarnos sus preferencias alimentarias al reservar.', 'Ja, unsere Speisekarte bietet mehrere vegetarische Gerichte. Teilen Sie uns Ihre Ernährungswünsche bei der Reservierung mit.', 3, true),
('Le restaurant est-il accessible aux personnes à mobilité réduite ?', 'Is the restaurant wheelchair accessible?', 'Il ristorante è accessibile alle persone con mobilità ridotta?', '¿El restaurante es accesible para personas con movilidad reducida?', 'Ist das Restaurant barrierefrei?', 'Oui, notre restaurant est accessible aux personnes à mobilité réduite. L''accès est de plain-pied depuis la place.', 'Yes, our restaurant is wheelchair accessible. There is step-free access from the square.', 'Sì, il nostro ristorante è accessibile alle persone con mobilità ridotta. L''accesso è a livello dalla piazza.', 'Sí, nuestro restaurante es accesible para personas con movilidad reducida. El acceso es a nivel desde la plaza.', 'Ja, unser Restaurant ist barrierefrei. Der Zugang vom Platz aus ist stufenlos.', 4, true),
('Avez-vous une terrasse ?', 'Do you have an outdoor terrace?', 'Avete una terrazza?', '¿Tienen terraza?', 'Haben Sie eine Terrasse?', 'Oui, nous disposons d''une belle terrasse ombragée sur la place Jean Jaurès, idéale pour profiter des beaux jours.', 'Yes, we have a lovely shaded terrace on Place Jean Jaurès, perfect for enjoying sunny days.', 'Sì, disponiamo di una bella terrazza ombreggiata sulla piazza Jean Jaurès, ideale per godersi le belle giornate.', 'Sí, disponemos de una bonita terraza sombreada en la plaza Jean Jaurès, ideal para disfrutar de los días soleados.', 'Ja, wir verfügen über eine schöne schattige Terrasse am Place Jean Jaurès, ideal für sonnige Tage.', 5, true),
('Acceptez-vous les réservations de groupe ?', 'Do you accept group reservations?', 'Accettate prenotazioni per gruppi?', '¿Aceptan reservas de grupo?', 'Akzeptieren Sie Gruppenreservierungen?', 'Oui, nous accueillons les groupes. Pour les tables de plus de 8 personnes, nous vous invitons à nous contacter directement par téléphone.', 'Yes, we welcome groups. For parties of more than 8, please contact us directly by phone.', 'Sì, accogliamo i gruppi. Per tavoli di più di 8 persone, vi invitiamo a contattarci direttamente per telefono.', 'Sí, recibimos grupos. Para mesas de más de 8 personas, le invitamos a contactarnos directamente por teléfono.', 'Ja, wir heißen Gruppen willkommen. Für Tische mit mehr als 8 Personen kontaktieren Sie uns bitte direkt telefonisch.', 6, true),
('Quels moyens de paiement acceptez-vous ?', 'What payment methods do you accept?', 'Quali metodi di pagamento accettate?', '¿Qué métodos de pago aceptan?', 'Welche Zahlungsmethoden akzeptieren Sie?', 'Nous acceptons les cartes bancaires (Visa, Mastercard), les espèces et les titres restaurant.', 'We accept credit cards (Visa, Mastercard), cash, and meal vouchers.', 'Accettiamo carte di credito (Visa, Mastercard), contanti e buoni pasto.', 'Aceptamos tarjetas bancarias (Visa, Mastercard), efectivo y vales de restaurante.', 'Wir akzeptieren Kreditkarten (Visa, Mastercard), Bargeld und Essensmarken.', 7, true),
('Y a-t-il un parking à proximité ?', 'Is there parking nearby?', 'C''è un parcheggio nelle vicinanze?', '¿Hay aparcamiento cerca?', 'Gibt es Parkplätze in der Nähe?', 'Oui, un parking gratuit se trouve à 2 minutes à pied du restaurant (parking de la Promenade). Des places de stationnement sont également disponibles sur la place.', 'Yes, a free car park is located 2 minutes'' walk from the restaurant (Promenade car park). Street parking is also available on the square.', 'Sì, un parcheggio gratuito si trova a 2 minuti a piedi dal ristorante (parcheggio della Promenade). Posti auto sono disponibili anche sulla piazza.', 'Sí, un aparcamiento gratuito se encuentra a 2 minutos a pie del restaurante (parking de la Promenade). También hay plazas de aparcamiento en la plaza.', 'Ja, ein kostenloser Parkplatz befindet sich 2 Gehminuten vom Restaurant entfernt (Parkplatz Promenade). Parkplätze sind auch auf dem Platz verfügbar.', 8, true);
